source 'https://rubygems.org'

gem 'jekyll'
gem "kramdown-parser-gfm"

group :jekyll_plugins do
  gem 'jekyll-feed', '0.11.0'
  gem 'jekyll-seo-tag', '2.5.0'
  gem 'jekyll-sitemap', '1.2.0'
  gem "jekyll-mentions", "1.6.0"
  gem "webrick"
end
