name: Publish Package to npmjs
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  # run-tests:
  #   uses: ./.github/workflows/test-node.yml

  build:
    # needs: [run-tests]
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
      - name: Cache node_modules
        uses: actions/cache@v5
        with:
          path: |
            **/node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn build:all
      - name: publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN > ~/.npmrc
          yarn publish_to_npm
